import 'package:flutter/material.dart';

class MyColor {

  static const Color white = Color(0xFFFFFFFF);
    static const Color bedge = Color(0xFFFFF3E0);
    static const Color yellow_splash = Color(0xFFFFCC80);
    static const Color grey_bg = Color(0xFFF5F5F5);
  static const Color grey_BG_main = Color(0xFFf9f9f9);
  static const Color grey_BG = Color(0xFFeeeeee);
  static const Color yellow_gradient1 = Color(0xFFFFFDE7);
  static const Color yellow_gradient2 = Color(0xFFFFF8E1);
  static const Color yellow_gradient3 = Color(0xFFFFE0B2);
  static const Color red = Color(0xFFFD4A4E);
  static const Color blue = Color(0xFF31C7F5);
  static const Color blue_fb = Color(0xFF1977F2);
  static const Color bluePink = Color(0xFF4D4DFE);
  static const Color blue_accent = Color(0xFF0082be);
  static final Color red_bg_opacity = const Color(0xFFFD4A4E).withOpacity(0.075);
  static const Color red_accent = Color(0xFFBD373A);
  static const Color red_pink_bg = Color(0xFFFEF6F8);
  static const Color grey = Color(0xFF8F8F8F);
  static const Color grey_background_blur = Color(0xFFFAFAFA);
  static const Color grey_background_blur2 = Color(0xFFF5F5F5);
  static const Color grey_line = Color(0xFFF5F5F5);
  static const Color green = Color(0xFF1ECB5D);
  static  Color greenOpa = Color(0xFF1ECB5D).withOpacity(.35);
  static const Color green_accent = Color(0xFF598066);
  static const Color green2 = Color(0xFF1ECB59);
  static const Color white_text = Color(0xFFFFFFFF);
  static const Color black_text = Color(0xFF2D2D2D);
  static const Color grey_text = Color(0xFF8F8F8F);
  static const Color red_text = Color(0xFFFD4A4E);
  static const Color yellow = Color(0xffffffc107);
  static const Color yellow_bg = Color(0xFFFFF9C4);
  static const Color yellow2 = Color(0xffFFC107);
  static const Color yellow3 = Color(0xffFFC107);
  static const Color yellow_accent = Color(0xFFc09935);
  static const Color blacklight = Color(0xFF424242);
  static const Color orange = Color(0xFFFE9433);
  static const Color pink = Color(0xFFFFC0CB);
  static const Color orange_accent = Color(0xFFA87954);
  static final Color red_bg = const Color(0xFFFEF6F8).withOpacity(0.75);
  static const Color grey_tab = Color(0xFFE0E0E0);
  static final Color grey_tab_opa = const Color(0xFFE0E0E0).withOpacity(.5);
  static const Color grey_tab3 = Color(0xFFD6D6D6);
  static const Color grey_tab2 = Color(0xFFF5F5F5);
  static const Color grey_icon = Color(0xFFE0E0E0);
  static final Color dialog = const Color(0xFFCAD3DE).withOpacity(0.5);
  static final Color dialog2 = const Color(0xFF8F8F8F).withOpacity(0.5);
  static const Color colorPrimary = Color(0xFFccaf75);
}
